### ISSUE TITLE
communicate with Arduino's RF24 library

### ISSUE THREAD

**Issue by aildar** [spirilis/Enrf24#6]
Which settings should I use to communicate with arduino?
Thank you

**Comment by spirilis** [comment]
I hear they do the address backwards.  Otherwise for RF settings just read their documentation and set the library up right.

**Comment by aildar** [comment]
Here is my code snipped

MSP side:

Enrf24 radio(P2_0, P2_1, P2_2);
const uint8_t txaddr[] = "evres";  // server

void setup() {
  SPI.begin();
  SPI.setDataMode(SPI_MODE0);
  SPI.setBitOrder(MSBFIRST);

  radio.begin(1000000, 76);
  //radio.setTXpower(-18);
  radio.setCRC(true, true);
  radio.setTXaddress((void*)txaddr);
}

void loop() {
    radio.write(txbuf, 11);
    radio.flush();
}

Arduino side:

uint8_t server_addr[] = "server";

void setup() {
  radio.begin();
  radio.setPALevel(RF24_PA_LOW);
  radio.enableDynamicPayloads();
  radio.openReadingPipe(1, server_addr);
  radio.startListening();
}

void loop() {
   radio.read(rmsg, 11);
}
